version: "3.9"
services:
  db:
    image: postgres:14.2-alpine
    container_name: rails_tutorial_db
    volumes:
      - rails_tutorial_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  app:
    build: .
    container_name: rails_tutorial_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    environment:
      DATABASE_URL: postgres://postgres:@db:5432
    ports:
      - 3010:3000
    depends_on:
      - db
    restart: always
    privileged: true
    tty: true
    stdin_open: true
volumes:
  rails_tutorial_db_data:
  bundle:
