default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  host: <%= ENV.fetch("DB_DEVELOPMENT_HOST") {Rails.application.credentials.database[:development_host]} %>
  database: <%= ENV.fetch("DB_DEVELOPMENT_DATABASE") {Rails.application.credentials.database[:development_db_name]} %>
  username: <%= ENV.fetch("DB_DEVELOPMENT_USERNAME") {Rails.application.credentials.database[:development_username]} %>
  password: <%= ENV.fetch("DB_DEVELOPMENT_PASSWORD") {Rails.application.credentials.database[:development_password]} %>

production:
  <<: *default
  host: <%= ENV.fetch("DB_PRODUCTION_HOST") {Rails.application.credentials.database[:production_host]} %>
  database: <%= ENV.fetch("DB_PRODUCTION_DATABASE") {Rails.application.credentials.database[:production_db_name]} %>
  username: <%= ENV.fetch("DB_PRODUCTION_USERNAME") {Rails.application.credentials.database[:production_username]} %>
  password: <%= ENV.fetch("DB_PRODUCTION_PASSWORD") {Rails.application.credentials.database[:production_password]} %>
